<a href="https://colab.research.google.com/github/heshChamika/Example/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Numpy arrays**

In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#creat Numpy ndarray object

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**NumPy array Indexing**

In [5]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [6]:
print(arr[1])

2


In [7]:
print(arr[2] + arr[4])

8


In [8]:
#Access 2D arrays

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd elemet on the 1st row :',arr[0,1])

2nd elemet on the 1st row : 2


**NumPy array slicing**

In [10]:
#[start:end]

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [12]:
print(arr[4:])

[5 6 7 8]


In [13]:
print(arr[:4])

[1 2 3 4]


**Numpy array copy vs view**

In [14]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5  6  7  8]
[42  2  3  4  5  6  7  8]


**NumPy array Reshaping**

In [16]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [18]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)
print('Shape of the array : ',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of the array :  (1, 1, 1, 1, 4)


In [19]:
# reshape 1D to 2D

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
#reshape 1D to 3D

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**NumPy array Iterating**

In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in arr:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]
